#!/bin/bash
# 部署 spabot_demo.php 到遠端伺服器

echo "=========================================="
echo "部署 LINE Bot 到遠端伺服器"
echo "=========================================="
echo ""

# 設定變數
LOCAL_FILE="/Volumes/aiserver2/spabot_demo.php"
REMOTE_HOST="www.twn.pw"
REMOTE_PATH="/path/to/line/spa/spabot_new.php"  # 請修改為實際路徑
REMOTE_USER="your_username"  # 請修改為實際用戶名

echo "檢查本地檔案..."
if [ ! -f "$LOCAL_FILE" ]; then
    echo "❌ 找不到本地檔案: $LOCAL_FILE"
    exit 1
fi
echo "✅ 本地檔案存在"
echo ""

echo "準備部署的檔案資訊:"
echo "  本地檔案: $LOCAL_FILE"
echo "  檔案大小: $(wc -c < "$LOCAL_FILE") bytes"
echo "  最後修改: $(stat -f "%Sm" "$LOCAL_FILE")"
echo ""

echo "遠端伺服器資訊:"
echo "  主機: $REMOTE_HOST"
echo "  用戶: $REMOTE_USER"
echo "  路徑: $REMOTE_PATH"
echo ""

echo "=========================================="
echo "部署步驟:"
echo "=========================================="
echo ""

echo "選項 1: 使用 SCP 上傳"
echo "----------------------------------------"
echo "指令:"
echo "  scp $LOCAL_FILE $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH"
echo ""

echo "選項 2: 使用 SFTP 上傳"
echo "----------------------------------------"
echo "步驟:"
echo "  1. 連接 SFTP: sftp $REMOTE_USER@$REMOTE_HOST"
echo "  2. 切換目錄: cd /path/to/line/spa/"
echo "  3. 上傳檔案: put $LOCAL_FILE spabot_new.php"
echo "  4. 確認上傳: ls -l spabot_new.php"
echo "  5. 離開: exit"
echo ""

echo "選項 3: 使用 FTP 客戶端 (例如 FileZilla)"
echo "----------------------------------------"
echo "步驟:"
echo "  1. 開啟 FileZilla"
echo "  2. 連接到 $REMOTE_HOST"
echo "  3. 導航到 /path/to/line/spa/"
echo "  4. 上傳 $LOCAL_FILE"
echo "  5. 重新命名為 spabot_new.php"
echo ""

echo "選項 4: 手動複製內容"
echo "----------------------------------------"
echo "步驟:"
echo "  1. 開啟本地檔案: $LOCAL_FILE"
echo "  2. 複製所有內容"
echo "  3. SSH 連接到遠端: ssh $REMOTE_USER@$REMOTE_HOST"
echo "  4. 編輯檔案: nano /path/to/line/spa/spabot_new.php"
echo "  5. 貼上內容並儲存"
echo ""

echo "=========================================="
echo "部署後驗證步驟:"
echo "=========================================="
echo ""
echo "1. SSH 連接到遠端伺服器"
echo "   ssh $REMOTE_USER@$REMOTE_HOST"
echo ""
echo "2. 檢查檔案是否存在"
echo "   ls -la /path/to/line/spa/spabot_new.php"
echo ""
echo "3. 檢查檔案內容（確認 API URL）"
echo "   grep '172.105.229.197' /path/to/line/spa/spabot_new.php"
echo ""
echo "4. 設定檔案權限"
echo "   chmod 644 /path/to/line/spa/spabot_new.php"
echo ""
echo "5. 清空日誌檔案（可選）"
echo "   > /path/to/line/spa/line_bot_log.txt"
echo ""
echo "6. 透過 LINE 發送測試訊息"
echo "   例如: 明天下午3點西門"
echo ""
echo "7. 檢查日誌"
echo "   tail -f /path/to/line/spa/line_bot_log.txt"
echo ""

echo "=========================================="
echo "重要提醒:"
echo "=========================================="
echo ""
echo "✅ 確認事項:"
echo "  □ Python API 在遠端伺服器運行 (172.105.229.197:5001)"
echo "  □ spabot_demo.php 中的 API URL 正確"
echo "  □ LINE Bot webhook URL 設定正確"
echo "  □ 檔案權限正確"
echo "  □ PHP 有寫入日誌檔案的權限"
echo ""
echo "⚠️  如果遠端伺服器無法運行 Python API:"
echo "  需要將 API URL 改為可訪問的地址"
echo "  例如: http://localhost:5001/parse"
echo "       (如果 API 和 PHP 在同一台伺服器)"
echo ""

echo "部署準備完成！請選擇上述方法之一進行部署。"
